export function removeAccentVowels(text: string): string {
  return text.replace(
    /[áàâãäÁÀÂÃÄ]|[éèêëÉÈÊË]|[íìîïÍÌÎÏ]|[óòôõöÓÒÔÕÖ]|[úùûüÚÙÛÜ]|[çÇ]/g,
    (match) => {
      const accents: { [key: string]: string } = {
        á: "a",
        à: "a",
        â: "a",
        ã: "a",
        ä: "a",
        Á: "A",
        À: "A",
        Â: "A",
        Ã: "A",
        Ä: "A",
        é: "e",
        è: "e",
        ê: "e",
        ë: "e",
        É: "E",
        È: "E",
        Ê: "E",
        Ë: "E",
        í: "i",
        ì: "i",
        î: "i",
        ï: "i",
        Í: "I",
        Ì: "I",
        Î: "I",
        Ï: "I",
        ó: "o",
        ò: "o",
        ô: "o",
        õ: "o",
        ö: "o",
        Ó: "O",
        Ò: "O",
        Ô: "O",
        Õ: "O",
        Ö: "O",
        ú: "u",
        ù: "u",
        û: "u",
        ü: "u",
        Ú: "U",
        Ù: "U",
        Û: "U",
        Ü: "U",
        ç: "c",
        Ç: "C",
      };
      return accents[match];
    },
  );
}
